SHOW DATABASES;
USE SAKILA;
SELECT database();
SHOW TABLES;
SELECT * FROM ACTOR;
DESC ACTOR;
SELECT ACTOR_ID FROM ACTOR;
SELECT ACTOR_ID, FIRST_NAME FROM ACTOR;
SELECT * FROM ACTOR WHERE ACTOR_ID=3;

-- DATA BASE FILTER

SELECT * FROM ACTOR WHERE ACTOR_ID BETWEEN 5 AND 10;
SELECT * FROM ACTOR WHERE ACTOR_ID IN (10,15,35,40,45);

SELECT * FROM ACTOR WHERE FIRST_NAME IN("ED","JOE");

SELECT * FROM ACTOR WHERE FIRST_NAME = "ED";
SELECT * FROM ACTOR WHERE FIRST_NAME LIKE "ED";

SELECT * FROM  ACTOR WHERE  FIRST_NAME LIKE "E%";

SELECT * FROM ACTOR WHERE FIRST_NAME LIKE  "%E";

SELECT * FROM ACTOR WHERE FIRST_NAME LIKE"R%A%";

SELECT * FROM ACTOR WHERE FIRST_NAME LIKE"R__A%";

SELECT  FIRST_NAME , LOWER(FIRST_NAME) FROM ACTOR;

SELECT FIRST_NAME , substr(FIRST_NAME , 4 ,5) AS 5WORDS FROM  ACTOR;

SELECT FIRST_NAME , substr(FIRST_NAME , -3 ,5) AS 5WORDS FROM  ACTOR;

SELECT FIRST_NAME , INSERT (FIRST_NAME,"E") FROM ACTOR;

SELECT FIRST_NAME,
       INSERT(FIRST_NAME, 2, 0, 'E') AS MODIFIED_NAME
FROM ACTOR;

SELECT FIRST_NAME , INSERT(FIRST_NAME,1,2,"R") AS MODIFIED FROM ACTOR;

SELECT FIRST_NAME , LAST_NAME , CONCAT(FIRST_NAME,"  ",LAST_NAME) AS ADDINTG FROM ACTOR;

SELECT "           HEY   " FROM DUAL;  

SELECT TRIM(LEADING " " FROM "             HEY           ") FROM DUAL; 

SELECT  FIRST_NAME ,LPAD(FIRST_NAME , 5,"#") FROM ACTOR;

SELECT FIRST_NAME ,REPLACE(FIRST_NAME , "E","#") FROM ACTOR;
